### ISSUE TITLE
Extra hearts don't fill when morphed with Identity

### ISSUE THREAD

**Issue by balt-dev** [emilyploszaj/trinket-heart-canisters#4]
Whenever I'm morphed into something with the Identity mod, and I apply heart canisters, the extra hearts don't fill.

https://user-images.githubusercontent.com/59123926/104260484-3dbbdd80-5449-11eb-8baf-ca0e68802849.mp4

**Comment by emilyploszaj** [comment]
This is likely due to how identity messes with the player's hearts and will have to be fixed by them.
