### ISSUE TITLE
Fabric Heart Canisters extra hearts do not fill when morphed

### ISSUE THREAD

**Issue by balt-dev** [emilyploszaj/trinket-heart-canisters#5]
Whenever I'm morphed into something with the Identity mod, and I apply heart canisters, the extra hearts don't fill.

Also see: https://github.com/emilyalexandra/trinket-heart-canisters/issues/4

https://user-images.githubusercontent.com/59123926/104260484-3dbbdd80-5449-11eb-8baf-ca0e68802849.mp4

**Comment by emilyploszaj** [comment]
Same answer as #4, this is something they have to fix
